# Autogenerated by devscripts/update-version.py

__version__ = '2024.04.10.030349'

RELEASE_GIT_HEAD = '8781ffb4f188267a382b18d3109a6f2f9029ecca'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'hugohaa/yt-dlp'

ORIGIN = 'hugohaa/yt-dlp'

_pkg_version = '2024.04.10.030349'
